name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
      with:
        version: 2.5.8
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIA5Z2MMKZFXCBKZ3OZ
        aws-secret-access-key: Wc9MmPj8JMBTt6+a5ZH+NpYQzba8klrs0AE6KkEd
        aws-region: us-east-1
        
    - name: Run Instance
      run: |
          aws ec2 run-instances --image-id ami-0f9fc25dd2506cf6d --count 1 --instance-type t2.micro \
          --key-name 220rsa --subnet-id subnet-0ee95324fdf68a500 --security-group-ids sg-05251f794e3a7021e \
          --user-data file://amazon_web_service.sh
