name: Run Tests
on: [push, pull_request]
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m venv .venv
          .venv/bin/pip install -r requirements.txt
      - name: Run Flask Server
        run: |
          .venv/bin/python3 test_app.py &
      - name: Install Plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Tests
        run: |
          .venv/bin/pytest
      - name: Insatll Pylint
        run: |
          pip install pylint
          pip install flask
          pip install python-dotenv
      - run: Run Pylint
          pylint -d invalid-name -d consider-using-with app.py
          pylint -d invalid-name -d consider-using-with -d missing-module-docstring -d missing-function-docstring test_app.py 
