name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Install AWS CLI
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
      with:
        version: 2.5.8
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Run Instance
      run: |
          aws ec2 run-instances --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=DevOps Project}]' --image-id ami-0f9fc25dd2506cf6d --count 1 --instance-type t2.micro --key-name ${{ secrets.KEY_NAME }} --security-group-ids ${{ secrets.SECURITY_GROUP }} --user-data file://${{github.workspace}}/amazon_web_service.sh > instance.txt
           INSTANCE_ID="$(grep -o '"InstanceId": "[^"]*' instance.txt | grep -o '[^"]*$')" 
           echo $INSTANCE_ID
